// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzAJ7Af8-Ba7pJWzZ5AXzM0bna0lMVXUo',
    appId: '1:798959788724:web:18bd16d6c8d6f10100ade1',
    messagingSenderId: '798959788724',
    projectId: 'mukbites-dfc31',
    authDomain: 'mukbites-dfc31.firebaseapp.com',
    storageBucket: 'mukbites-dfc31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWnbrecUr1dyqh3Vi6jcTbKKjcWAXOP4',
    appId: '1:798959788724:android:0bf607c077d23fb800ade1',
    messagingSenderId: '798959788724',
    projectId: 'mukbites-dfc31',
    storageBucket: 'mukbites-dfc31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzAJ7Af8-Ba7pJWzZ5AXzM0bna0lMVXUo',
    appId: '1:798959788724:ios:9980b9b2f4e1bacd00ade1',
    messagingSenderId: '798959788724',
    projectId: 'mukbites-dfc31',
    storageBucket: 'mukbites-dfc31.firebasestorage.app',
    iosBundleId: 'com.example.makbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzAJ7Af8-Ba7pJWzZ5AXzM0bna0lMVXUo',
    appId: '1:798959788724:macos:9980b9b2f4e1bacd00ade1',
    messagingSenderId: '798959788724',
    projectId: 'mukbites-dfc31',
    storageBucket: 'mukbites-dfc31.firebasestorage.app',
    iosBundleId: 'com.example.makbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzAJ7Af8-Ba7pJWzZ5AXzM0bna0lMVXUo',
    appId: '1:798959788724:web:9980b9b2f4e1bacd00ade1',
    messagingSenderId: '798959788724',
    projectId: 'mukbites-dfc31',
    authDomain: 'mukbites-dfc31.firebaseapp.com',
    storageBucket: 'mukbites-dfc31.firebasestorage.app',
  );

} 
